PaddlePaddle/hapi

mnist.py
model.py
resnet.py
yolov3.py

write access does not seem to work due to paddlepaddle default repo permissions.

Add model API and demo

---

callbacks.py
metrics.py
model.py
progressbar.py
tests/test_callbacks.py
tests/test_model.py
tests/test_progressbar.py

- Add ProgressBar
- Add callback
- Add fit 
callback example:
```
class ModelCheckpoint(Callback):
def __init__(self, save_freq=1, save_file='output'):
self.save_freq = save_freq
self.save_file = save_file
def on_epoch_begin(self, epoch=None, logs=None):
self.epoch = epoch
def on_epoch_end(self, step, logs=None):
if self.model and self.epoch % self.save_freq == 0:
path = '{}/{}'.format(self.save_file, step)
print('save checkpoint at {}'.format(path))
self.model.save(path)
def on_train_end(self, logs=None):
if self.model:
path = '{}/final'.format(self.save_file)
print('save checkpoint at {}'.format(path))
self.model.save(path)
```

Add fit in Model

---

model.py

To support fine-tuning, add `reset_optimizer, layers, weights` arguements for `model.load`. 
Currently, a feasible way for fine-tuning  is given in [YOLOv3 demo](https://github.com/PaddlePaddle/hapi/blob/master/yolov3.py#L513), which is implemented by integrating a backbone model `backbone_model` into a full model `full_model` and use `full_model.backbone_model.load`. However,  this needs a way to  ignore the saved optimizer states. Thus we add the `reset_optimizer` argument.
Additionally, add `layers` and `weights` arguments for partial loading. The usage is as follows:
```python
guard = fluid.dygraph.guard() if True else null_guard()
inputs = [Input([None, in_size], "float32", name="x")]
labels = [Input([None, 1], "int64", name="label")]
class MyModel(Model):
def __init__(self): …
```

Support for fine-tuning.

---

callbacks.py
distributed.py
mnist.py
model.py
tests/test_model.py

1. remove init_context
2. init multiple in model __init__
3. set place again in model __init__
4. remove get_local_rank and get_nranks, use Env() instead
5. remove some noused import
6. remove DistributedDataParallel

remove init_context

---

model.py
progressbar.py

Reorganize data from data_loader into inputs and labels.

Reorganize data from data_loader into inputs and labels.

---

lac.py

add_lac_model

---

models/tsm.py
yolov3/dataset/download_voc.py

**fix tsm.py and yolov3/dataset/download_voc.py**
- fix `models/tsm.py` not pushed
- fix `yolov3/dataset/download_voc.py` download import path

fix tsm.py and yolov3/dataset/download_voc.py

---

model.py
models/yolov3.py
yolov3/coco.py
yolov3/main.py
yolov3/transforms.py

**extract input variable from feed**
- fix unused feed Variable pruned by CompilePorgram

extract input variable from feed

---

examples/bmn/eval.py
examples/bmn/predict.py
examples/bmn/reader.py
examples/bmn/train.py
hapi/callbacks.py
hapi/vision/models/__init__.py
hapi/vision/models/bmn_model.py

**update BMN**
TODO in next pr
- update release weights
- unify `fluid.layers.create_parameter`
- extract parameter from config in `examples/train.py` and call `bmn` with given parameter instead of `cfg`
- add `filelist` arguments in `infer.py`
- update doc

update BMN format

---

examples/bmn/bmn_metric.py
hapi/metrics.py
hapi/model.py

**refine metric usage and add doc**

refine metric

---

examples/image_classification/README.MD
examples/image_classification/main.py
examples/image_classification/scripts/mobilenet_v1_x1.0.sh
examples/image_classification/scripts/mobilenet_v2_x1.0.sh
examples/image_classification/scripts/resnet101.sh
examples/image_classification/scripts/resnet152.sh
examples/image_classification/scripts/resnet18.sh
examples/image_classification/scripts/resnet34.sh
examples/image_classification/scripts/resnet50.sh
examples/image_classification/scripts/vgg16.sh
hapi/model.py
hapi/vision/models/mobilenetv1.py
hapi/vision/models/mobilenetv2.py
hapi/vision/models/resnet.py
hapi/vision/models/vgg.py
hapi/vision/transforms/transforms.py

1. 发布resnet18，resnet34， resnet101，resnet152，4个预训练模型
2. 修复了一些文档问题
3. 图像分类模型添加了定义类别等参数
4. 修复了QA测试的一些问题

release some image classification models

---

examples/bmn/README.md
examples/bmn/bmn.yaml
examples/bmn/bmn_metric.py
examples/bmn/eval.py
examples/bmn/predict.py
examples/bmn/run.sh
examples/bmn/train.py
hapi/vision/models/bmn_model.py

refine details of bmn model, following #36

refine details of bmn model

---

examples/tsm/infer.py
examples/tsm/main.py
examples/tsm/transforms.py
examples/yolov3/main.py
examples/yolov3/transforms.py
hapi/datasets/flowers.py
hapi/datasets/mnist.py
hapi/vision/transforms/transforms.py

**refine compose**
- refine compose in `vision/transforms/transform.py` support both single field and multi-fields
- remove `Compose` in `yolov3` `tsm` transforms

refine compose

---

examples/bert/bert_classifier.py
examples/bert/run_classifier_single_gpu.sh
examples/bert_leveldb/bert_classifier.py
examples/bert_leveldb/run_classifier_multi_gpu.sh
examples/bert_leveldb/run_classifier_single_gpu.sh
hapi/text/bert/__init__.py
hapi/text/bert/bert.py
hapi/text/bert/dygraph_optimization.py
hapi/text/bert/optimization.py
hapi/text/bert/static_optimization.py
hapi/text/text.py

1) update bert to support static-graph training.
2) refine loading pre-trained parameters
3) fix some bugs  in text.py

update bert and text.py

---

hapi/tests/test_model.py

Fix unittest for predict and evaluate.

Fix unittest for predict and evaluate

---

examples/bmn/reader.py

fix bmn bug, data type missmatch in windows

fix bmn bug, data type missmatch in windows

---

examples/bmn/README.md
examples/bmn/bmn.yaml
examples/bmn/eval.py
examples/bmn/predict.py
examples/bmn/train.py

refine README and details of bmn model

refine README and details of bmn model

---

examples/seq2seq/README.md
examples/seq2seq/predict.py
examples/seq2seq/train.py
examples/transformer/predict.py
examples/transformer/train.py

Fix seq2seq and transformer on cpu.

Fix seq2seq and transformer on cpu

---

examples/bert/bert_classifier.py
examples/bert/readme.md
examples/bert/run_classifier_multi_gpu.sh

change bert code (examples/bert) for QA testing

change bert for QA

---

examples/seq2seq/README.md

fix seq2seq README.md

---

examples/seq2seq/seq2seq_attn.py
examples/seq2seq/seq2seq_base.py
examples/seq2seq/train.py
examples/seq2seq/utility.py
examples/sequence_tagging/eval.py
examples/sequence_tagging/predict.py
examples/sequence_tagging/reader.py
examples/sequence_tagging/sequence_tagging.py
examples/sequence_tagging/train.py
examples/sequence_tagging/utils/check.py
examples/sequence_tagging/utils/configure.py
examples/sequence_tagging/utils/metrics.py
examples/transformer/transformer.py

Make Transformer, seq2seq, sequence_tagging adapt to paddle.incubate.hapi

Make Transformer, seq2seq, sequence_tagging adapt to paddle.incubate.hapi

---

examples/bmn/bmn_metric.py
examples/bmn/eval.py
examples/bmn/modeling.py
examples/bmn/predict.py
examples/bmn/reader.py
examples/bmn/run.sh
examples/bmn/train.py

transfer bmn model hapi interface to paddle2.0

transfer bmn model hapi interface to paddle2.0

---

tsm/infer.py
tsm/main.py
tsm/modeling.py

update TSM use new APIS

---

yolov3/darknet.py
yolov3/infer.py
yolov3/main.py
yolov3/modeling.py

**update yolov3 use new API.**

update yolov3 use new API.

---

yolov3/dataset/download_voc.py

**fix download_voc use new APIs**

fix download_voc

---

tsm/main.py
tsm/modeling.py
yolov3/main.py

**Update TSM use 2.0 API**
Tested on static/dynamic train/eval/infer ok
```
Eval begin...
step 10/25 - loss: 0.4631 - acc_top1: 0.7638 - acc_top5: 0.9700 - 736ms/step
step 20/25 - loss: 1.0517 - acc_top1: 0.7394 - acc_top5: 0.9763 - 621ms/step
step 25/25 - loss: 0.0023 - acc_top1: 0.7632 - acc_top5: 0.9887 - 577ms/step
Eval samples: 386
```

Update TSM use 2.0 API

---

tsm/main.py
tsm/modeling.py
yolov3/main.py
yolov3/modeling.py

**update optimizer API for TSM & YOLOv3**

update optimizer API for TSM & YOLOv3

---

tsm/README.md
tsm/infer.py
tsm/main.py
tsm/modeling.py
tsm/transforms.py
yolov3/README.md
yolov3/darknet.py
yolov3/infer.py
yolov3/main.py
yolov3/modeling.py
yolov3/transforms.py

**set_device after enable_static**

set_device after enable_static & 2d -> 2D & --dynamic -> --static

---

tsm/infer.py
yolov3/coco.py
yolov3/infer.py

fix TSM & YOLOv3

---

README.md

fix code which missing paddle.Model

fix code in readme
